---
- name: deployment
  hosts: all
  become: True
  vars:
    nexus_url: http://18.118.170.113:8081/repository
    repository_type: mymaven-releases
    group_id: com/mycompany/app
    artifact_id: my-app
    version: 1.6.2
    build_number: "{{build_number}}"
  tasks:
  - name: Download file from a file path
    ansible.builtin.get_url:
      url: "{{nexus_url}}/{{repository_type}}/{{group_id}}/{{artifact_id}}/{{version}}.{{build_number}}/{{artifact_id}}-{{version}}.{{ build_number}}.jar"
      dest: /usr/share/tomcat/webapps
      username: admin
      password: afrin
  - name: restart systemd, enable tomcat service and start tomcat service
    ansible.builtin.systemd:
       name: tomcat.service
       daemon-reload: yes
       state: started
       enabled: yes